Public Enum CardType
    AceOfWands
    TwoOfWands
    ThreeOfWands
    FourOfWands
    FiveOfWands
    SixOfWands
    SevenOfWands
    EightOfWands
    NineOfWands
    TenOfWands
    PageOfWands
    KnightOfWands
    QueenOfWands
    KingOfWands
    AceOfCups
    TwoOfCups
    ThreeOfCups
    FourOfCups
    FiveOfCups
    SixOfCups
    SevenOfCups
    EightOfCups
    NineOfCups
    TenOfCups
    PageOfCups
    KnightOfCups
    QueenOfCups
    KingOfCups
    AceOfSwords
    TwoOfSwords
    ThreeOfSwords
    FourOfSwords
    FiveOfSwords
    SixOfSwords
    SevenOfSwords
    EightOfSwords
    NineOfSwords
    TenOfSwords
    PageOfSwords
    KnightOfSwords
    QueenOfSwords
    KingOfSwords
    AceOfPentacles
    TwoOfPentacles
    ThreeOfPentacles
    FourOfPentacles
    FiveOfPentacles
    SixOfPentacles
    SevenOfPentacles
    EightOfPentacles
    NineOfPentacles
    TenOfPentacles
    PageOfPentacles
    KnightOfPentacles
    QueenOfPentacles
    KingOfPentacles
    TheFool
    TheMagician
    TheHighPriestess
    TheEmpress
    TheEmperor
    TheHierophant
    TheLovers
    TheChariot
    Strength
    TheHermit
    WheelOfFortune
    Justice
    TheHangedMan
    Death
    Temperance
    TheDevil
    TheTower
    TheStar
    TheMoon
    TheSun
    Judgement
    TheWorld
End Enum
