Imports System.Runtime.CompilerServices

Friend Module CardTypes
    Friend ReadOnly Descriptors As IReadOnlyDictionary(Of CardType, ICardType) =
        New List(Of ICardType) From
        {
            New CardTypeDescriptor(CardType.AceOfCups, "Ace of Cups"),
            New CardTypeDescriptor(CardType.TwoOfCups, "Two of Cups"),
            New CardTypeDescriptor(CardType.ThreeOfCups, "Three of Cups"),
            New CardTypeDescriptor(CardType.FourOfCups, "Four of Cups"),
            New CardTypeDescriptor(CardType.FiveOfCups, "Five of Cups"),
            New CardTypeDescriptor(CardType.SixOfCups, "Six of Cups"),
            New CardTypeDescriptor(CardType.SevenOfCups, "Seven of Cups"),
            New CardTypeDescriptor(CardType.EightOfCups, "Eight of Cups"),
            New CardTypeDescriptor(CardType.NineOfCups, "Nine of Cups"),
            New CardTypeDescriptor(CardType.TenOfCups, "Ten of Cups"),
            New CardTypeDescriptor(CardType.PageOfCups, "Page of Cups"),
            New CardTypeDescriptor(CardType.KnightOfCups, "Knight of Cups"),
            New CardTypeDescriptor(CardType.QueenOfCups, "Queen of Cups"),
            New CardTypeDescriptor(CardType.KingOfCups, "King of Cups"),
            New CardTypeDescriptor(CardType.AceOfSwords, "Ace of Swords"),
            New CardTypeDescriptor(CardType.TwoOfSwords, "Two of Swords"),
            New CardTypeDescriptor(CardType.ThreeOfSwords, "Three of Swords"),
            New CardTypeDescriptor(CardType.FourOfSwords, "Four of Swords"),
            New CardTypeDescriptor(CardType.FiveOfSwords, "Five of Swords"),
            New CardTypeDescriptor(CardType.SixOfSwords, "Six of Swords"),
            New CardTypeDescriptor(CardType.SevenOfSwords, "Seven of Swords"),
            New CardTypeDescriptor(CardType.EightOfSwords, "Eight of Swords"),
            New CardTypeDescriptor(CardType.NineOfSwords, "Nine of Swords"),
            New CardTypeDescriptor(CardType.TenOfSwords, "Ten of Swords"),
            New CardTypeDescriptor(CardType.PageOfSwords, "Page of Swords"),
            New CardTypeDescriptor(CardType.KnightOfSwords, "Knight of Swords"),
            New CardTypeDescriptor(CardType.QueenOfSwords, "Queen of Swords"),
            New CardTypeDescriptor(CardType.KingOfSwords, "King of Swords"),
            New CardTypeDescriptor(CardType.AceOfPentacles, "Ace of Pentacles"),
            New CardTypeDescriptor(CardType.TwoOfPentacles, "Two of Pentacles"),
            New CardTypeDescriptor(CardType.ThreeOfPentacles, "Three of Pentacles"),
            New CardTypeDescriptor(CardType.FourOfPentacles, "Four of Pentacles"),
            New CardTypeDescriptor(CardType.FiveOfPentacles, "Five of Pentacles"),
            New CardTypeDescriptor(CardType.SixOfPentacles, "Six of Pentacles"),
            New CardTypeDescriptor(CardType.SevenOfPentacles, "Seven of Pentacles"),
            New CardTypeDescriptor(CardType.EightOfPentacles, "Eight of Pentacles"),
            New CardTypeDescriptor(CardType.NineOfPentacles, "Nine of Pentacles"),
            New CardTypeDescriptor(CardType.TenOfPentacles, "Ten of Pentacles"),
            New CardTypeDescriptor(CardType.PageOfPentacles, "Page of Pentacles"),
            New CardTypeDescriptor(CardType.KnightOfPentacles, "Knight of Pentacles"),
            New CardTypeDescriptor(CardType.QueenOfPentacles, "Queen of Pentacles"),
            New CardTypeDescriptor(CardType.KingOfPentacles, "King of Pentacles"),
            New CardTypeDescriptor(CardType.AceOfWands, "Ace of Wands"),
            New CardTypeDescriptor(CardType.TwoOfWands, "Two of Wands"),
            New CardTypeDescriptor(CardType.ThreeOfWands, "Three of Wands"),
            New CardTypeDescriptor(CardType.FourOfWands, "Four of Wands"),
            New CardTypeDescriptor(CardType.FiveOfWands, "Five of Wands"),
            New CardTypeDescriptor(CardType.SixOfWands, "Six of Wands"),
            New CardTypeDescriptor(CardType.SevenOfWands, "Seven of Wands"),
            New CardTypeDescriptor(CardType.EightOfWands, "Eight of Wands"),
            New CardTypeDescriptor(CardType.NineOfWands, "Nine of Wands"),
            New CardTypeDescriptor(CardType.TenOfWands, "Ten of Wands"),
            New CardTypeDescriptor(CardType.PageOfWands, "Page of Wands"),
            New CardTypeDescriptor(CardType.KnightOfWands, "Knight of Wands"),
            New CardTypeDescriptor(CardType.QueenOfWands, "Queen of Wands"),
            New CardTypeDescriptor(CardType.KingOfWands, "King of Wands"),
            New CardTypeDescriptor(CardType.TheFool, "The Fool(0)"),
            New CardTypeDescriptor(CardType.TheMagician, "The Magician(I)"),
            New CardTypeDescriptor(CardType.TheHighPriestess, "The High Priested(II)"),
            New CardTypeDescriptor(CardType.TheEmpress, "The Empress(III)"),
            New CardTypeDescriptor(CardType.TheEmperor, "The Emperor(IV)"),
            New CardTypeDescriptor(CardType.TheHierophant, "The Hierophant(V)"),
            New CardTypeDescriptor(CardType.TheLovers, "The Lovers(VI)"),
            New CardTypeDescriptor(CardType.TheChariot, "The Chariot(VII)"),
            New CardTypeDescriptor(CardType.Strength, "Strength(VIII)"),
            New CardTypeDescriptor(CardType.TheHermit, "The Hermit(IX)"),
            New CardTypeDescriptor(CardType.WheelOfFortune, "Wheel of Fortune(X)"),
            New CardTypeDescriptor(CardType.Justice, "Justice(XI)"),
            New CardTypeDescriptor(CardType.TheHangedMan, "The Hanged Man(XII)"),
            New CardTypeDescriptor(CardType.Death, "Death(XIII)"),
            New CardTypeDescriptor(CardType.Temperance, "Temperance(XIV)"),
            New CardTypeDescriptor(CardType.TheDevil, "The Devil(XV)"),
            New CardTypeDescriptor(CardType.TheTower, "The Tower(XVI)"),
            New CardTypeDescriptor(CardType.TheStar, "The Start(XVII)"),
            New CardTypeDescriptor(CardType.TheMoon, "The Moon(XVIII"),
            New CardTypeDescriptor(CardType.TheSun, "The Sun(XIX)"),
            New CardTypeDescriptor(CardType.Judgement, "Judgement(XX)"),
            New CardTypeDescriptor(CardType.TheWorld, "The World(XXI)")
            }.ToDictionary(Function(x) x.CardType, Function(x) x)
    <Extension>
    Friend Function ToDescriptor(cardType As CardType) As ICardType
        Return Descriptors(cardType)
    End Function
End Module
